### ISSUE TITLE
plugin doesn't refresh collections

### ISSUE THREAD

**Issue by Grzegorzsa** [dboissier/mongo4idea#104]
When I remove collection using plugin and recreate it manulally, new collection is not beign shown.
I use refresh button, but it doesn't help.
plugin v 0.70 , WebStrom 8.05, Windows 7 - 64

**Comment by dboissier** [comment]
You may need to refresh your server by right-clicking on the server node and select Refresh this server

**Comment by Grzegorzsa** [comment]
It worked, thanks
