### ISSUE TITLE
can you have a table view

### ISSUE THREAD

**Issue by hugcoday** [dboissier/mongo4idea#105]
curent view style  is tree view ,it good ,but I like table view ,most developer come from mysql ,oracle.

can you supply a table view. thanks for you

sorry for my poor english.

**Comment by dboissier** [comment]
Hi,

No more features will be implemented in the mongo plugin (Check README). I focus on nosql plugin that will integrate mongo, couchbase and redis databases.

However, I put your suggestion in the ToDo list.

**Comment by dboissier** [comment]
This feature is currently on progress.

**Comment by dboissier** [comment]
In the latest 0.9.0 (At the right of the toolbar of the result view)
