### ISSUE TITLE
shellArguments appears to not be working

### ISSUE THREAD

**Issue by dayjobtitus** [dboissier/mongo4idea#110]
In line 93 of file below I think you have a bug, but if not, then not sure why arguments aren't working. Also authentication appears to not work. 

src/main/java/org/codinjutsu/tools/mongo/view/console/MongoConsoleRunner.java 
92          if (StringUtils.isNotBlank(shellArgumentsLine)) {
93              commandLine.addParameters(shellArgumentsLine.split(" "));
94          }

**Comment by babielvs** [comment]
It seems like --authenticationDatabase <dbname> not working, because of spliting the arguments.

**Comment by dboissier** [comment]
Hi,

Does it work on the latest 0.7.2 version?

**Comment by babielvs** [comment]
No it doesn´t. Maybe my config is wrong: 

Console (works): 

mongo db1 --host localhost -u username1 -p password1  --authenticationDatabase admin

Plugin:
Server url: localhost:27017

Authenntication settings
Username: username1
Password: password1
Auth. database: admin

**Comment by dboissier** [comment]
Thx for your feedback. I will check that

**Comment by dboissier** [comment]
Hi,

it may be related to the mispelling of the **authenticationMechanism** option  (I forgot the h letter in mechanism).

I have some spare time today, I will provide a snapshot ASAP.

FYI, there is a big issue with **2016** version of Jetbrains products. The settings of the plugin are not displayed when clicking the icon. I will rewrite this part in order not to be dependent on the Settings Panel.

**Comment by dboissier** [comment]
Hi,

the 0.9.0 should fix the issue you encounter. Please confirm or reject.

**Comment by babielvs** [comment]
authentication works, thank you
