### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by andreybolonin** [dboissier/mongo4idea#111]
17:26:13 MongoTimeoutException: Error when accessing Mongo server: Timed out after 10000 ms while waiting for a server that matches {serverSelectors=[ReadPreferenceServerSelector{readPreference=primary}, LatencyMinimizingServerSelector{acceptableLatencyDifference=15 ms}]}. Client view of cluster state is {type=ReplicaSet, servers=[{address=ordernode10:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: ordernode10: unknown error}}, {address=ordernode11:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: ordernode11: unknown error}}, {address=ordernode12:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.UnknownHostException: ordernode12: unknown error}}]

Any ideas?

Thank you.

**Comment by dboissier** [comment]
Hi,

Is your mongo server is configured as replicat set?
If yes, you have to precise the host field in the following way:
`replicat_set_host_1:port,replicat_set_host_2:port,...`

Regards

**Comment by SierraGolf** [comment]
I had the same problem. The reason was that I was not specifying the right host and port, which was definitely my fault.

However, the plugin blocks the whole IDE when it waits for the timeout to kick in, which for me is 30000ms. This gives a really bad user experience.

I am using Idea Ultimate 14.1.3 and the plugin at version: 0.7.1

**Comment by dboissier** [comment]
Hi,

I will fix that. Please confirm this happens in the Mongo Explorer Panel.

Regards,

David

**Comment by navi8602** [comment]
MongoTimeoutException: Error when collecting Mongo databases: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=141.8.193.225:28017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]

**Comment by dboissier** [comment]
Hi, 

please install manually this [SNAPSHOT version](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.2-SNAPSHOT-distribution.zip) and tell me if it works on your side.

Thanks.

**Comment by SierraGolf** [comment]
works (better) for me. a few improvements:

1. when I click on the database while there is no connection here is no feedback. maybe a dialog saying connection can not be established makes sense.
2. when the connection gets lost while the database is already "open" and I select a collection, it still hangs.
3. when the database connection establishes after an offline period and you have tried to click on it in that period, for every click you made the database shows the names of the databases duplicated. this only fixes by clicking on "refresh from server"

**Comment by dboissier** [comment]
Hi,

thanks for your suggestion. I will improve UI reactivity.

**Comment by dboissier** [comment]
@SierraGolf about the 3rd suggestion, could you please be more precise or provide a screenshot?

Regards,

David

**Comment by SierraGolf** [comment]
Sure, steps to reproduce:

1. start up local mongo server with a database called "test"
2. open IDE
3. configure mongo server connection in IDE
4. close IDE
5. stop mongo server
6. open IDE
7. click five times on previously configured mongo server connection (nothing will happen)
8. start up mongo server
9. IDE will automatically connect and show five times the test database for the configured connection
10. right-click on connection to refresh from server to resolve the duplicate entries

**Comment by dboissier** [comment]
Hi @SierraGolf ,

Please test the latest snapshot and tell me if it is ok for you

**Comment by SierraGolf** [comment]
yeah, works much better now.

**Comment by SierraGolf** [comment]
can you also provide a version for idea 15?

**Comment by dboissier** [comment]
Hi,

please test the following [SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.3-SNAPSHOT-distribution.zip) and tell me if it works on Idea 15.

Thanks.

**Comment by SierraGolf** [comment]
works. thanks for you effort!
