### ISSUE TITLE
BsonInvalidOperationException loading collection

### ISSUE THREAD

**Issue by O1O1O1O** [dboissier/mongo4idea#115]
When trying to open some collections of my Mongo database I get this error:

org.bson.BsonInvalidOperationException: readString can only be called when CurrentBSONType is STRING, not when CurrentBSONType is SYMBOL

Others open fine.  I think this might be a driver problem.  See this [bug report](https://jira.mongodb.org/browse/JAVA-1909)

**Comment by dboissier** [comment]
upgraded to 3.0.4 in the latest 0.7.2 snapshot
