### ISSUE TITLE
IntellijIdea 14.1.4

### ISSUE THREAD

**Issue by ntenisOT** [dboissier/mongo4idea#119]
First of all thanks for the great plugin.

Unfortunately, I cannot connect to my MongoLab server. 

I get the following error:

    21:18:40 MongoTimeoutException: Error when collecting Mongo databases: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=ds039073.mongolab.com:39073, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'auth failed' on server ds039073.mongolab.com:39073. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 }}}]

If you have time please take a look! :)

**Comment by dboissier** [comment]
Hi, 

please install manually this [SNAPSHOT version](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.2-SNAPSHOT-distribution.zip) and tell me if it works on your side.

Thanks.

**Comment by jblankendaal** [comment]
I didn't open the Issue, but I can confirm that this allows me to connect to MongoLab using the plugin on Intellij 14.1.5 (OSX, extract in directory ~/Library/Application Support/IntelliJIdea14/mongo4idea-0.7.2)

Thanks for this nice plugin!
