### ISSUE TITLE
Use aggregates to query

### ISSUE THREAD

**Issue by jbpotonnier** [dboissier/mongo4idea#12]
Aggregate pipeline is rich and generic. It may be a good and easy way to express queries

**Comment by ethicalvats** [comment]
Hi @dboissier the plugin is great, but it lacks passing the additional options to aggregate pipeline for example allowDiskUse, cursor batch size, collation and index hints. Putting here the mongo aggregate link as a [reference](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/)
