### ISSUE TITLE
Webstorm 11 - NoClassDefFoundError

### ISSUE THREAD

**Issue by Swissbite** [dboissier/mongo4idea#120]
Opening a shell is not possible.
NoClassDefFoundError: **com/intellij/execution/runners/ConsoleExecuteActionHandler**

**Comment by dboissier** [comment]
Hi,

please test the following [SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.3-SNAPSHOT-distribution.zip) and tell me if it works on Idea 15.

Thanks.

**Comment by Swissbite** [comment]
It's working and also in intelliJ 15 as mentioned in #121
Thank you.
