### ISSUE TITLE
NoClassException IDEA 15

### ISSUE THREAD

**Issue by Jazed** [dboissier/mongo4idea#121]
10:32:08 PM NoClassDefFoundError: com/intellij/execution/runners/ConsoleExecuteActionHandler

Every time I try to open the shell.

**Comment by jakubov** [comment]
Hi David
I am getting the following error when I click on the add server in mongo plugin in PyCharm.
Any idea what might be the issue?
12:17:28 AM NoClassDefFoundError: com/mongodb/AuthenticationMechanism

**Comment by dboissier** [comment]
Hi @Jazed,

I have to compile mongo plugin for Idea 15. I use a component from the platform source code (so this is a deep component, not a component from their plugin api).
 So each time they release a major version, I have this runtime exception. I will fix it today.

Sorry for the inconvenience.

**Comment by dboissier** [comment]
Hi @jakubov,

Please look at your PyCharm workspace `<user>/.PyCharm/config/plugins/`  
First, check you only have one instance of the plugin in this directory
Second, check the following file in `mongo4idea-0.7.2/lib`;
* `mongo-java-driver-3.0.4.jar`

If not, please reinstall the plugin.
If yes, which PyCharm version do you have?

**Comment by jakubov** [comment]
hey @dboissier 
i have a <user>/.PyCharm40 ..but I am not seeing any /config/plugins folder under it.
I use PyCharm 4.5.

**Comment by dboissier** [comment]
This is strange.
 Usually, plugins are installed in this folder. How your PyCharm workspace is structured?

**Comment by Jazed** [comment]
Hi @dboissier 

Thanks for the response! Let me know once you've pushed the update.

**Comment by jakubov** [comment]
@dboissier 
when I installed PyCharm on my Mac, I just took the defaults.  Where should I look for the workspace settings/structure ?

**Comment by dboissier** [comment]
@jakubov 

Usually Jetbrains IDE create a workspace (.WebStorm6, .IntellijIdea14, .PyCharm6) in the user home directory.

In this folder all your global settings are saved, including third party plugin you install from jetbrains repository.

Let me give some time to install a PyCharm on my mac and I check what is going on.

**Comment by dboissier** [comment]
Hi @Jazed and @jakubov,

please test the following [SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.3-SNAPSHOT-distribution.zip) and tell me if it works on Idea 15.

Thanks.

**Comment by Jazed** [comment]
@dboissier it works now thanks a lot

**Comment by dboissier** [comment]
Great. 

I will make an official release tomorrow.

Thanks for your patience

**Comment by jakubov** [comment]
PyCharm now says "Plugin 'Mongo Plugin' is incomapatible with this installation

**Comment by dboissier** [comment]
Hi @jakubov,

Do you confirm you have `~/Library/Application Support/PyCharmXX` folder?
If yes, you should find the mongo4idea plugin within.
Please confirm you have `mongo-java-driver-3.0.2.jar` under `mongo4idea-0.7.2/lib`

**Comment by jakubov** [comment]
Here is what I got :

~/Library/Application Support/PyCharm40
○ → ls
availables.xml			mongo-java-driver-3.0.4.jar
extensions.xml			mongo4idea-0.7.3-SNAPSHOT.jar
idea-gitignore.jar

**Comment by dboissier** [comment]
Quite strange. Normally, you should have the following structure:
```
~/Library/Application Support/PyCharm40
|
+--mongo4idea-0.7.2/
   |
   +--lib/
      |
      +--mongo4idea-0.7.2.jar
      +--mongo-java-driver-3.0.4.jar
```

Anyway, as first fix, you should remove ` mongo-java-driver-3.0.4.jar` and `mongo4idea-0.7.3-SNAPSHOT.jar`.

Download from your browser this [version](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.2-SNAPSHOT-distribution.zip) (the same but compatible with your PyCharm version) and unzip it into `~/Library/Application Support/PyCharm40`.

Restart your IDEA and tell me if it works.

**Comment by jakubov** [comment]
the download link you provided is still the SNAPSHOT.

**Comment by dboissier** [comment]
Yes, but this is the **0.7.2** version instead of 0.7.3 which is incompatible with your PyCharm version.

**Comment by jakubov** [comment]
thx a lot ... that worked!

**Comment by dboissier** [comment]
Great! Thx for your patience.
