### ISSUE TITLE
Cannot locate Mongo shell console under IntelliJ Tools

### ISSUE THREAD

**Issue by AaronJessen** [dboissier/mongo4idea#125]
I'm using IntelliJ v15, and the I've configured the settings to point to my mongo.exe. However, the Mongo shell console option is not appearing under the Tools menu item, as shown in the GitHub instructions. Is the shell currently unavailable in this release?

**Comment by dboissier** [comment]
Hi,

You may setup several replica sets in the server configuration. The console is unavailable because detecting the master replica set is quite difficult.
To fix that you could setup one host.

Tell me if it works and check if you can make some writing operations.

Thanks

**Comment by AaronJessen** [comment]
Thanks for your reply, David. I attempted to register (alone, as you suggested) the 3 different MongoDB hosts I use (localhost included, which does not have multiple replica sets), and none allowed the MongoDB Console option to appear under the Tools menu.

I'd very much like to use this inside IntelliJIs, as the other features you've built into the plugin are superior to any other GUI I've used. Is there anything else I can do?

________________________________

**Comment by dboissier** [comment]
All suggestions about UX or features are welcomed :)

**Comment by AaronJessen** [comment]
I'm sorry, but I may have been unclear in my last post. The issue is still unresolved.

For the sake of this discussion, let's just say that I have a single MongoDB instance, hosted at `localhost:27017`. It is a new database with only one collection in it, and the database does not have multiple replica sets. When I configure that server within your plugin's settings, there **still** isn't a `Console` option appearing under the `Tools` menu, as you detailed in the instructions.

Is there anything else you can suggest that I try in order to see the `Console` option?

**Comment by dboissier** [comment]
Sorry for misreading your post.

The documentation is outdated :(.

Actually, you need to select a database under your mongo server node and the button will appear in the toolbar.

**Comment by AaronJessen** [comment]
Okay, I see it now. Thanks, again, for such an awesome plugin!
