### ISSUE TITLE
Unable to use plugin PHPStorm 10.0.1

### ISSUE THREAD

**Issue by plexus77** [dboissier/mongo4idea#126]
I have recently installed your plugin but am unable to see the icons for adding a server.

![screen shot 2015-11-24 at 12 59 53 pm](https://cloud.githubusercontent.com/assets/1281305/11355750/8a08e83c-92ab-11e5-95a8-5e4e34c49b07.png)

**Comment by plexus77** [comment]
I am able to configure the server via preferences -> other settings -> mongo servers.

**Comment by dboissier** [comment]
Clicking on the wrench icon on the toolbar opens the Server configuration dialog too
