### ISSUE TITLE
"Error 8: Auth fail" on my pc with IDEA 14

### ISSUE THREAD

**Issue by JonasGao** [dboissier/mongo4idea#127]
I use this plugin connect to my MongoDb. but fail...

MongoDB Version=3.x
exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='admin', source='mydb', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 10.0.0.*:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]

**Comment by dboissier** [comment]
Hi,

Does the latest version work on your IDEA?
