### ISSUE TITLE
How to query on a date object? 

### ISSUE THREAD

**Issue by guggens** [dboissier/mongo4idea#129]
hi, I have a working mongo connection, and queries on strings are working fine, when entered in the filter section.
when querying a specific date, I could not figure out a syntax for specifying a date, the usual .js approach does not seem to work:

created_at: {
        $gte: ISODate("2010-04-29T00:00:00.000Z"),
        $lt: ISODate("2010-05-01T00:00:00.000Z")
    }

How can this be done? maybe you can add some more samples to the main page.

thanks!

**Comment by dboissier** [comment]
Hi,

please look at the post #86 
You right. I should add some query samples in the doc.

Regards,

David.
