### ISSUE TITLE
What is the mongo executable?

### ISSUE THREAD

**Issue by sanjaypoyzer** [dboissier/mongo4idea#130]
In the screenshot for setting up the server, the Path to Mongo executable is `/usr/bin/mongo`. I've only ever used `mongo` from the command line to access the database and I don't seem to have anything in that location. Is there something missing from my Mongo install?

Installed via Homebrew on Mac OSX 10.11.

**Comment by pablote** [comment]
if you installed via homebrew, you most probably have the executable on `/usr/local/bin/mongo`

**Comment by sanjaypoyzer** [comment]
Ah awesome, thanks! That did it for me. 🎉

Now I just need to work out what the rest of the login info is... 😕

**Comment by rob-balfre** [comment]
:thumbsup: thanks helped me too

**Comment by fuxiangduan** [comment]
不能感谢更多:thumbsup:
