### ISSUE TITLE
Unable to open mongo shell

### ISSUE THREAD

**Issue by pablote** [dboissier/mongo4idea#131]
I can connect to the database and everything seems to work well, except when trying to open a mongo shell. This error shows up: 

`Error parsing command line: unrecognised option '--authenticationMecanism'
try '/usr/local/bin/mongo --help' for more information`

thanks

**Comment by hallowei** [comment]
me too~

**Comment by dastrobu** [comment]
I have a similar problem. Can't open the mongo shell but with a different error message: 
`Error parsing command line: unrecognised option '--username'
try '/usr/local/bin/mongod --help' for more information`

I'm running `MongoDB shell version: 3.2.0`

**Comment by dboissier** [comment]
Hi,

does the bug still occur with the latest `0.11.0` version?
