### ISSUE TITLE
Mongo Shell disabled (greyed out=

### ISSUE THREAD

**Issue by mwestermann** [dboissier/mongo4idea#135]
I am on OS X El Capitan and both in Webstorm 10 and PHPStorm 10 I experience that the Mongo Explorer is working fine and can connect to the database w/o any problems, but the icon for the Mongo Shell is greyed out and nothing happens when I click it.

Does it need special rights or do I need to enable it somewhere?

**Comment by dboissier** [comment]
Hi,

Did you set the mongo cli path?
If yes, is your mongo url is a single instance or a list of replicat set?

Regards

**Comment by mwestermann** [comment]
I did set the CLI path and it seems that the IDE is accepting it and as you can see from the attached file the URL is a single instance.
<img width="1047" alt="screen shot 2016-01-14 at 12 28 46" src="https://cloud.githubusercontent.com/assets/10298450/12323332/b20d1b6e-baba-11e5-8ecd-b0cb607944b2.png">

**Comment by dboissier** [comment]
Actually, you have to select a database first and then the Shell button will be enabled

**Comment by mwestermann** [comment]
Sorry - My bad! Never occurred to me. Feel kinda stupid now.

Tnx. for your help :-)

**Comment by dboissier** [comment]
Do not feel stupid. I think this is a UX issue because some users encountered the same problem.

I should hide it if you do not select a database.

What do you think about this proposal?

**Comment by mwestermann** [comment]
Instead of hiding it, which will also lead to confusion. I suggest that you enable it regardless of whether the user has selected a database or not. 

If the user has not selected a database, inform them in the Mongo Shell window, that they have to select a db before they can use the shell for anything. 

I guess it will be easy to implement and it will guide the user to take the correct action.

**Comment by dboissier** [comment]
good idea
