### ISSUE TITLE
Date pickup changes the date when editing a document

### ISSUE THREAD

**Issue by mmnaseri** [dboissier/mongo4idea#137]
When editing a document which has a date field, the pickup will choose one day prior to the date I pick, so if for instance I pick `2016-01-21` it sets it to `2016-01-20`.

My timezone is -8:00 and the time is set properly, however, the date is changed automatically to one day before the day I choose. This might be because the dropdown is converting the date without adjusting for the timezone or something of the same ilk.

**Comment by dboissier** [comment]
Hi,

I will redesign the edition so I will fix the Datepicker behavior

**Comment by dboissier** [comment]
fixed in the last 0.12.0
