### ISSUE TITLE
Cannot add mongo server

### ISSUE THREAD

**Issue by greenlaw110** [dboissier/mongo4idea#140]
When I click the Mongo Settings icon it pops up the plugins dialog directly and there is no place for me to add the server:

![image](https://cloud.githubusercontent.com/assets/216930/12568220/6522a230-c418-11e5-99c3-e88c46bde80c.png)

I am on IntelliJ IDEA v15.0.3, Mint 17.3

**Comment by asmoores** [comment]
+1

**Comment by dboissier** [comment]
Hi,

Which Intellij version do you use?

Actually, the settins are under **Other Settings** section but this is strange, it does not forward you directly.

Regards,

David

**Comment by asmoores** [comment]
Hi David

I'm using the latest CE version 15.04.  I can see the dialog under Other Settings.  The Mongo Settings button is opening Preferences but the last time I viewed is selected rather than Mongo Servers.

Regards
Andrew

**Comment by andkuzmich** [comment]
I have the same issue

**Comment by shooltz** [comment]
I have the same issue. RubyMine 8.0.3

**Comment by dboissier** [comment]
Found the root cause. Will provide a fix ASAP

**Comment by dmsovetov** [comment]
Same thing with 0.7.3 and this IDE:

IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_91-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by dboissier** [comment]
Hi,

Does it work with the latest version of the plugin?
