### ISSUE TITLE
Mongo Explorer seems stuck in windowed mode

### ISSUE THREAD

**Issue by mccart** [dboissier/mongo4idea#146]
Just installed mongodb plugin into Intellj IDEA 2016.1
In settings, windowed mode - the mongodb popped out as independent window.
Selected the floating mode (expecting it to reintegrate into IDEA window), it stayed
as independent window...  Is this expected?

**Comment by dboissier** [comment]
Hi,

This is independant from the plugin. It seems the latest version of Intellij has some issues with its windows dock.
