### ISSUE TITLE
'Unable to authorize' when connecting to mongolab

### ISSUE THREAD

**Issue by ujjwal96** [dboissier/mongo4idea#148]
Using mongo plugin 0.7.0 with PyCharm 4.0.5
Whenever I try to connect to my mongolabs server it says
Error when accessing Mongo server: { "serverUsed" : "ds0XXXXX-a.mlab.com:XXXXX" , "ok" : 0.0 , "errmsg" : "auth failed" , "code" : 18}
X= Port No.
However I'm able to connect to it using mongo shell

**Comment by dboissier** [comment]
Hi,

do you have a restricted access to this database?

**Comment by ujjwal96** [comment]
Just updated PyCharm to 4.5 and plugin to 7.2
It's working now!
Thanks
