### ISSUE TITLE
Passwords that have special characters present might not work properly

### ISSUE THREAD

**Issue by BlackBsd** [dboissier/mongo4idea#149]
When using the plugin, i have noticed that if my username's password had the letter '@' present, then authentication would always fail.

**Comment by dboissier** [comment]
Hi,

 I need to encode the password when I generate the mongo URI.

**Comment by dboissier** [comment]
Similar to #145

**Comment by dboissier** [comment]
Hi,

Does the latest version of  the plugin work on your IDE?

**Comment by BlackBsd** [comment]
I am sorry, i have not had a chance to try out the new plugin.  I am not sure if this issue is still present or not.

**Comment by dboissier** [comment]
The latest version I pushed few weeks ago should fix it but I want to make sure with your feedback ;)
