### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by david-navarro** [dboissier/mongo4idea#151]
Can I connect to mongodb via SSH conn?

**Comment by dboissier** [comment]
Hi,

The plugin uses the mongo java driver which does not support SSH tunneling. 

Sorry for the inconvenience.

**Comment by mdcotter** [comment]
Is there any plan to add SSH Tunneling?

**Comment by dboissier** [comment]
Actually not. If the mongo-java-driver plans to support it, I will update the plugin.

**Comment by dboissier** [comment]
I saw some [snippets ](https://kahimyang.com/kauswagan/code-blogs/1337/ssh-tunneling-with-java-a-database-connection-example)to use a SSH tunneling to connect to a MySQL database.

I will make a try and let you know when you can test it.

**Comment by webdevilopers** [comment]
:+1: @dboissier . I know you are no longer maintaining this project and switched to https://github.com/dboissier/nosql4idea. Are you still planning to implement SSH Tunnel somewhere?

**Comment by dboissier** [comment]
To answer your question, yes I will make a try on mongo4idea and if it works fine, I will merge the code on the nosql4idea

Here below the reasons:
* nosql4idea is not ready for release. It takes time and focus and my bandwidth on it is empty
* There are many user of mongo4idea and it is important to take care of them. The updates are small and easy to code.

**Comment by webdevilopers** [comment]
Thanks for the update and the support @dboissier !

**Comment by dboissier** [comment]
Hi,

I am working on the SSH Tunneling support and I would need a sample configuration that I could test.
Any body can help me on that?

(If info is sensitive, then you can email to me at david DOT boissier AT gmail DOT com)

**Comment by webdevilopers** [comment]
Unfort. I only have 2 servers of customers where I'm not allowed to forward any credentials @dboissier . :(

**Comment by dboissier** [comment]
Ok,
What is the most common usage: local, remote or dynamic port forwarding?

**Comment by webdevilopers** [comment]
Not sure what you mean @dboissier . We connect on a SSH address on port *22* while the Server itself connects on *27017* of the localhost. Auth mode via private keys.

Does this help?

**Comment by dboissier** [comment]
Hi,

SSH Tunneling is working :). In you configuration, do you have replica set?

In my current understand of SSH tunneling, each remote server to reach should have a local port forwarding. Is that correct or not?

**Comment by webdevilopers** [comment]
:+1: I think so yes! That local port is **27017** I think @dboissier .

**Comment by david-navarro** [comment]
thanks for update @dboissier. 
I don't find where I can configure ssh params?

**Comment by dboissier** [comment]
If you installed the latest build available in the home page, you should see SSH Tunneling Tab in the Server Configuration Panel.
By default, the tunnel uses the 9080 port. Please tell me whether it works on your side.

**Comment by webdevilopers** [comment]
Though I see the SSH Tunneling Tab, where can I put my private key instead of username and password @dboissier ?

**Comment by dboissier** [comment]
Hi @webdevilopers. I need to code it. I will keep you inform when a build is available.
