### ISSUE TITLE
source cannot be null

### ISSUE THREAD

**Issue by Delagen** [dboissier/mongo4idea#153]
when i leave UserDatabase empty

**Comment by dboissier** [comment]
Hi,

do you have any stackstrace or screenshot?

Thx

**Comment by Delagen** [comment]
![2016-06-08 15 11 25](https://cloud.githubusercontent.com/assets/783335/15893940/8f1dfbde-2d8b-11e6-94c3-c752a6c8559f.png)
![2016-06-08 15 11 32](https://cloud.githubusercontent.com/assets/783335/15893941/8f38f6e6-2d8b-11e6-85fb-47dfd2d69d72.png)

**Comment by dboissier** [comment]
Root cause identified. Will fix it ASAP.

Thanks for reporting this bug

**Comment by dboissier** [comment]
Hi,

you will find 0.8.0 build links on the home page. Please get the version suitable to your IDE and tell me whether it works.

thanks

**Comment by linoliveira** [comment]
It works on 0.8.0 with PhpStorm 2016.
Thanks

**Comment by dboissier** [comment]
Great, I will deploy it ASAP. Thanks
