### ISSUE TITLE
Cannot connect to different database other than user database

### ISSUE THREAD

**Issue by rpavlicek** [dboissier/mongo4idea#164]
Our MongoDB servers use the admin database to store all user data. Other databases contain the data collections.

I want to connect to database 'abc', but my user information (and authentication credentials) are stored in the 'admin' db.

This plugin seems to lack the basic functionality of switching or browsing databases on the same MongoDB server. Most clients (MongoHub for example) have this functionality.

**Comment by erlik28** [comment]
I'm getting the same thing. Could it be some config issue? I tried with a different client and the other databases appear.

**Comment by dboissier** [comment]
Fixed in the latest 0.8.0 (Idea 15) or 0.8.1 (Idea 2016).  Please confirm.
