### ISSUE TITLE
The default authentication mechanism does not work with 3.2.5

### ISSUE THREAD

**Issue by odupuy** [dboissier/mongo4idea#166]
Intellij on Mac. MongoDB shell version: 3.2.5
Plug-in downloaded today 2016/09/12

If I use the default authentication, I have this error (2). 
I have to force the SCRAM-SHA-1 mechanism which is the new default in 3.X (https://docs.mongodb.com/manual/core/authentication/)

![screen shot 2016-09-13 at 15 49 24](https://cloud.githubusercontent.com/assets/3653807/18489108/30650e3a-79ca-11e6-9cb9-528b4291b86e.png)

The 'cancel' button does not work BTW, I have to wait for the error message.

The label for the 'user database' field says "if your access is restricted to a single database... you can set it right here.
At the same time, if empty the 'Test' fails with "source can( )not be null".
So it looks more mandatory than the label says.

**Comment by gregorskii** [comment]
+1

**Comment by dboissier** [comment]
There was a bug related to the auth database. A hot fix has been deployed. Please confirm or reject it.

**Comment by odupuy** [comment]
Merci David.
I have updated the plug-in and restarted my IDEA Mac (2016-2 pro with all the updates).
I am still using the docker mongo distribution https://hub.docker.com/_/mongo. (3.2.5)

My configuration which worked previously (username entered, password entered and SCRAM-SHA-1 selected) does not work with the update. Clicking on Test Connection, I get **"Test connection failed, source cannot be null"**.

To make it work, I have to enter in the "Auth. database" the same value as in the User Database field. I am a Mongo newbie. I found this [link](https://docs.mongodb.com/manual/reference/program/mongo/#mongo-shell-authentication-mechanisms) explaining that in absence of an authorization database specified with --authenticationDatabase then the same database is used.
I can test it on the command line, these two commands work OK the same way
>mongo localhost:27017/dcs -u myUser -p myPassword
>mongo localhost:27017/dcs -u myUser -p myPassword --authenticationDatabase dcs

I suggest adding this behavior of using the above value if "Auth. database" is empty.

If I select MONGODB-CR, it does not work, as expected, authorization database entered or not.

If I select "Default", if "Auth. database" is empty I get the above "Test connection...be null". If I enter the value, I get the same error as in the image above.

**Comment by odupuy** [comment]
I would also suggest to refresh the screenshots and explanations of the README. Thanks for your work David.

**Comment by dboissier** [comment]
Thanks Olivier for your feedback. I will make that change.

Regards

**Comment by nanothermite** [comment]
+1

**Comment by mihaisimi** [comment]
It worked for me with SCRAM-SHA-1 and Auth.database set.
 
I had to make sure my user had root access for the admin database, otherwise the plugin would fail complaining about not having access to list collections.

I don't think this is a problem for most dev environments, I am listing the command here in case somebody needs it: 
db.grantRolesToUser( "MYUSER", [ "root" ] )

**Comment by reypm** [comment]
@dboissier this still a bug in the latest version ...

> org.codinjutsu.tools.mongo.logic.ConfigurationException: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:9080, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

I am connecting to a given DB with an non privileged user. Any advice on the issue?

**Comment by dboissier** [comment]
Hi,

Do you need to provide credentials? If yes, which is the authentication database? Usually, this is the `admin` one.

Regards

**Comment by reypm** [comment]
@dboissier I've provided admin credentials to connect to MongoDB but the user I am using in the DB where I want to perform something is not an admin user is a non privileged user

**Comment by dboissier** [comment]
@reypm Sure! Please provide a snapshot and blur confidential data if needed.

Thanks

**Comment by mmi-rperez** [comment]
@dboissier ok, here you go:

![screenshot from 2017-01-09 12-22-37](https://cloud.githubusercontent.com/assets/22330735/21776375/207825fc-d668-11e6-80d2-813435d8e480.png)
![screenshot from 2017-01-09 12-28-48](https://cloud.githubusercontent.com/assets/22330735/21776374/20749ffe-d668-11e6-8f1a-7ac89f5bb2ab.png)
![screenshot from 2017-01-09 12-22-50](https://cloud.githubusercontent.com/assets/22330735/21776372/207467b4-d668-11e6-9b45-9e4d5b6deb1b.png)
![screenshot from 2017-01-09 12-22-57](https://cloud.githubusercontent.com/assets/22330735/21776373/2074b3ea-d668-11e6-8e23-22409f372f34.png)
![screenshot from 2017-01-09 12-23-03](https://cloud.githubusercontent.com/assets/22330735/21776376/2079021a-d668-11e6-8513-4ef765125995.png)

**Comment by reypm** [comment]
@dboissier here you go


![screenshot from 2017-01-09 12-22-37](https://cloud.githubusercontent.com/assets/627886/21777736/196b10e8-d66e-11e6-88f7-7118b19af308.png)
![screenshot from 2017-01-09 12-28-48](https://cloud.githubusercontent.com/assets/627886/21777732/1961b5b6-d66e-11e6-9ffe-ca2d68a8926e.png)
![screenshot from 2017-01-09 12-22-50](https://cloud.githubusercontent.com/assets/627886/21777735/19683b84-d66e-11e6-9a53-9a7b38503a8e.png)
![screenshot from 2017-01-09 12-22-57](https://cloud.githubusercontent.com/assets/627886/21777734/196638e8-d66e-11e6-8e9b-6b23d8208c0b.png)
![screenshot from 2017-01-09 12-23-03](https://cloud.githubusercontent.com/assets/627886/21777733/19662646-d66e-11e6-8f21-5fec1840a183.png)

**Comment by dboissier** [comment]
Hi @reypm, I fixed some bugs related to SSH tunneling in the latest `0.11.0` version of the plugin.

**Comment by reypm** [comment]
@dboissier thank you, I will give this a try as soon as I can and will let you know
