### ISSUE TITLE
can't see mapping lines in mongo explorer

### ISSUE THREAD

**Issue by giovanniciriello** [dboissier/mongo4idea#169]

**Comment by giovanniciriello** [comment]
This is the desired result:
https://raw.githubusercontent.com/dboissier/mongo4idea/master/doc/mongo4idea-collectionTabView.png

This is what i see
https://s11.postimg.org/i371cw237/Cattura.png

**Comment by dboissier** [comment]
Hi,

could you please provide more detail with both expected and actual results?

Thanks

**Comment by giovanniciriello** [comment]
If you notice the images, in the expected image there are lines that "underline" the concept of hierarchy of json objects

**Comment by dboissier** [comment]
In the example of the documentation you mention, the blurred lines are actually the representation of an array of String.
The sample JSON object used was an extraction of my previous project
```json
{
  "_id": "aef12345...",
  "name": "neko",
  "features": [
    "featureA," "featureB", "featureC"
  ]
}
```

The plugin returns a list of documents. So the output result would be displayed as follow:
```
[0]
    "_id"          "aef12345..."
    "name"         "neko"
    "features"
        [0]        "featureA"
        [1]        "featureB"
        [2]        "featureC"
```

What is the JSON object you want to display?
