### ISSUE TITLE
webstorm gathers upto 1G2 of mem and 30..40% of cpu

### ISSUE THREAD

**Issue by pixsrv** [dboissier/mongo4idea#171]
~~While plugin is installed and enabled (to be used) and mongo server is up (no matter if it runs from webstorm or from cmd) then webstorm gathers a lot of resources, works very slow up to stop working at all.~~
~~Issue was discussed with JB developer but they cannot find a cause in WS.~~
~~cpu jumps from 30..40 up to 70%~~

~~All above disappears and WS works perfectly when plugin is disabled.~~

**Comment by dboissier** [comment]
??

**Comment by dboissier** [comment]
??

**Comment by dboissier** [comment]
Your comment is strikethrough. What should I do to help you?

**Comment by pixsrv** [comment]
I'm trying to find out why Webstorm gathers mem and cpu extensively and i was sure that your plugin causes this. But I was wrong. Webstorm does it without your plugin also :(
Issue to close I suppose. 
thanx dboissier
