### ISSUE TITLE
Enhancement : shortcuts

### ISSUE THREAD

**Issue by brainztorm** [dboissier/mongo4idea#174]
Hi thanks for this plugin ! :)
It would be cool to have some shortcuts to open a collection, drop a collection or the database etc ...

Thanks and have a great day !

**Comment by dboissier** [comment]
Hi,

Thanks for your suggestion. I will look at it.
Do not hesitate to list other relevant shortcuts.

**Comment by dboissier** [comment]
* Open a collection: `F4`
* Drop collection: `DELETE`
* Drop database: `DELETE`

Is that ok? Others actions which could have a shortcut?

Thx
