### ISSUE TITLE
[MongoPlugin] java.lang.String cannot be cast to org.bson.types.ObjectId

### ISSUE THREAD

**Issue by JosefBoukal** [dboissier/mongo4idea#176]
**Environment**
Mac OS X El Capitan
Idea 2016.3 and 2016.2
Mongo Plugin: 0.9.2016
Java 1.8.0_74

**How to reproduce**
I have a collection with String type "_id". When I Edit a document and hit Save button I get the java.lang.String cannot be cast to org.bson.types.ObjectId.

**Comment by dboissier** [comment]
Hi,

`_id` is usually for `ObjectId`.

**Comment by JosefBoukal** [comment]
Hi,

I don't agree with your proposals. I downgraded to version **0.8.1** of this plugin and it is working correctly. According to the MongoDB documentation:

- The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, **and may be of any type other than an array**.

**See also**
https://docs.mongodb.com/manual/core/document/
http://stackoverflow.com/questions/11090446/can-i-use-string-as-id-type-for-mongodb-document

Cheers and thanks for your support.

Josef

**Comment by dboissier** [comment]
Hi,

Could you please add the stackstrace?

Thanks

**Comment by JosefBoukal** [comment]
Hi David,

Sorry, but there is no StackTrace in the IntelliJ IDEA log files. The error was shown on the screen with red colour only and the given message was logged in the Event Log view as well. Can't you reproduce the error as described above in the issue?

**Comment by dboissier** [comment]
Sure. Will check tomorrow.

**Comment by dboissier** [comment]
Hi,

There is a SNAPSHOT build available on the home page of the project. Please confirm it fixes the issue you encounter, or reject ;).

**Comment by JosefBoukal** [comment]
Hi Dave,

Thank you for a quick fix, I shall confirm that the issue doesn't occur on the 0.10.0-SNAPSHOT build with Idea 2016.3 any more.

Cheers
