### ISSUE TITLE
Filter freezes intellij with bad input

### ISSUE THREAD

**Issue by ProductOfAmerica** [dboissier/mongo4idea#177]
Filtering by an object (not in json format) will freeze the entire (jetbrains product) window.

![webstorm_2016-11-29_14-51-39](https://cloud.githubusercontent.com/assets/14712114/20728437/5897572c-b643-11e6-9a73-c037cd220429.png)

It is permanantly stuck on "Loading..." and the entire program is unresponsive.

Way to replicate:
1. Type in the world "hi" into the filter.
2. Press ctrl+ENTER
3. BUG

**Comment by dboissier** [comment]
Hi,

Thanks for reporting it (similar to #168)

**Comment by dboissier** [comment]
Hi,

please install the latest SNAPSHOT build available on the home page of the project and tell me whether the bug is fixed or not.

Thx
