### ISSUE TITLE
SSH private key authentication

### ISSUE THREAD

**Issue by sepam** [dboissier/mongo4idea#189]
#Is is possible to connect to a remote Mongo instance using SSH private key authentication?

**Comment by danielkay** [comment]
+1

**Comment by bastoune** [comment]
+1

**Comment by dunghv** [comment]
+1

**Comment by monobook** [comment]
+1

**Comment by gnillev** [comment]
+1

**Comment by Double1996** [comment]
+1

**Comment by pacanukeha** [comment]
+1

**Comment by dalejohnston** [comment]
+1

**Comment by dboissier** [comment]
Hi,

I am almost done with the SSH private key feature. What behavior would you like to have ? Asking the passphrase each time you connect to the server or store it temporary (cleared whenever you quit IntelliJ) ?

**Comment by monobook** [comment]
I guess It will be nice to store or handle by "KeyRing" (like database plugin do, once and forever :) )

**Comment by dboissier** [comment]
ok.

**Comment by dboissier** [comment]
My concern about asking the passphrase each time (it means for each operation) is the user experience could be damaged.

What is your point of view?

**Comment by monobook** [comment]
Why? As developer I don't want to enter each time my passphrase even I have 1234foobar. In this case  IDEA store keys in key ring like a charm :)

**Comment by dboissier** [comment]
Hi,

a SNAPSHOT is available [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)

FYI, this version does not use the Password Manager of IntelliJ. I still study it and I wait for your feedback on the SSH auth with Private key.

Support Intellij 2016+
