### ISSUE TITLE
Add "Delete Document" action

### ISSUE THREAD

**Issue by mklueh** [dboissier/mongo4idea#192]
I often need to remove documents from my collection during development, so it would be nice to have a "Delete Document" button in the context menu ;)

**Comment by dboissier** [comment]
Hi,

you need to edit the document first and you have a delete button.
This is not convenient, I will improve it by moving this action in the contextual menu with a Confirmation Popup.

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)
