### ISSUE TITLE
How do I get count of records in a collection matching a search query?

### ISSUE THREAD

**Issue by ALeschinsky** [dboissier/mongo4idea#195]
Please document this as it's probably one of the more used features other than simple `find` - I'm guessing there's a way to do this with Projection window, but how exactly can I do this?

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip). I added row count info.
Please note that for performance reason, the row limit is set to 300 documents. You can unset it to get all docs from your collection.

**Comment by dboissier** [comment]
Sorry, I misunderstood your original question. I currently work on showing stats of a collection including count, size and other data

From now, unless your collection contains too many document, you can remove the row limit value from the toolbar of the collection view, re-run the query and you will see the documents count below the panel (see screenshot at this [here](https://github.com/dboissier/mongo4idea#mongo-collection-tab-view).

Hope it helps.

**Comment by dboissier** [comment]
related to #216

**Comment by ALeschinsky** [comment]
That's not the same though - that's just getting all documents and checking the total count of records received. That won't work for large collections, I just want to execute the actual `.count()` in mongo - is that possible?

**Comment by dboissier** [comment]
from the mongo shell, yes.
Today, I will deploy a SNAPSHOT of the next version of the plugin, you will be able to see stats from collection and database. Hop it will match with your expectations

**Comment by dboissier** [comment]
Hi,

Please find [0.12.0-SNAPSHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.12.0-SNAPSHOT.zip).
When selecting database of collection, you will see the stats of the selected item.

The UI still need some improvements, so feedbacks are welcomed ;)
