### ISSUE TITLE
How do you create collection from Mongo Explorer?

### ISSUE THREAD

**Issue by snytkine** [dboissier/mongo4idea#199]
Is there a feature to create a new collection in database? I could not find one.
Strangely I also don't see mongo shell button. I did add path to mongo client and tested with test button and it was a successful test. Still no mongo shell button.

**Comment by dboissier** [comment]
Hi,

There is no action for creating Collection because it is easy to add a document in a new collection with mong cli.

**Comment by dboissier** [comment]
You can see the mongo cli button whenever you select a database
