### ISSUE TITLE
MongoDB 3.4 compatibility ?

### ISSUE THREAD

**Issue by ccpalmer** [dboissier/mongo4idea#200]
This cool plugin doesn't appear to work with MongoDB **3.4**.  Lots of things broke with 3.4, so it's not surprising.  Here's the error window I'm getting:

![image](https://user-images.githubusercontent.com/4670554/27644756-52424c56-5bf2-11e7-9047-d38d967808a7.png)

Ping me if you need more info...  

ccp

**Comment by luizvnasc** [comment]
Same here...

**Comment by jcdude** [comment]
I can connect and it display the databases but it will not load the collections.
Nothing in the logs either

**Comment by alek4k** [comment]
yeah, same problem for me. I can connect but can't load the collections

**Comment by dboissier** [comment]
Hi,

I will have some bandwidth starting from August.

Thanks for your patience :).

Regards.

**Comment by Gorbush** [comment]
Well, it works for me for simple cases - on 3.4.4:
[initandlisten] db version v3.4.4
[initandlisten] git version: 888390515874a9debd1b6c5d36559ca86b44babd
[initandlisten] OpenSSL version: OpenSSL 1.0.2l  25 May 2017

However when i try to use aggregation - it hangs in two seconds.

**Comment by rmaes4** [comment]
I am unable to connect to my remote mLab database running version 3.4.6

**Comment by jrdzha** [comment]
Hi, any news on this?

**Comment by kick-the-bucket** [comment]
Still a problem...

**Comment by dboissier** [comment]
I will start build some SNAPSHOT the next week. Thanks for being patient all this time.

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)

**Comment by juergenzimmermann** [comment]
Thank you @dboissier . The snapshot works fine with a MongoDB 4.0 database.
