### ISSUE TITLE
Out of memory error due to default Row limit

### ISSUE THREAD

**Issue by jevertz** [dboissier/mongo4idea#202]
Hi,

I encountered an out of memory error when trying to open a table with rather big rows (including binaries).
PyCharm and IntelliJ, both 2017. Increasing the memory settings might have helped, but it is slow, too.
So reducing the default Row limit to 10 and rebuilding the plugin solved the problem for me.
Perhaps it is worth considering adding the Row limit to the settings.

Btw.: The plugin is great.

**Comment by dboissier** [comment]
Hi,

I will add this in the plugin settings as `default row limit`

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)
