### ISSUE TITLE
mongo plugin is incompatiable with this installation

### ISSUE THREAD

**Issue by Aoterr** [dboissier/mongo4idea#209]
plugin is  mongo4idea-0.10.15-distribution.zip  and idea is 2017.3

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)

**Comment by dboissier** [comment]
Tested the plugin on 2017.3. Works fine.
