### ISSUE TITLE
Feature: order the databases and/or add filter in the Mongo Explorer view

### ISSUE THREAD

**Issue by fgm** [dboissier/mongo4idea#211]
When a connection has many databases, it becomes difficult to find the database one is looking for because the databases are listed out of order.

It would be much simpler if they were ordered or if a type-in filter was available.

**Comment by dboissier** [comment]
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)
