### ISSUE TITLE
Can't add server

### ISSUE THREAD

**Issue by Andruno** [dboissier/mongo4idea#215]
Hi! Can you explain please how I can add and connect to this server (Atlas Cluster from Mongo Explorer)?:

`mongo "mongodb://cluster0-shard-00-00-jxeqq.mongodb.net:27017,cluster0-shard-00-01-jxeqq.mongodb.net:27017,cluster0-shard-00-02-jxeqq.mongodb.net:27017/aggregations?replicaSet=Cluster0-shard-0" --authenticationDatabase admin --ssl -u m121 -p aggregations --norc`

**Comment by dboissier** [comment]
In the server settings, set your cluster in the server url field as follow and tell me if it works or not `cluster0-shard-00-00-jxeqq.mongodb.net:27017,cluster0-shard-00-01-jxeqq.mongodb.net:27017,cluster0-shard-00-02-jxeqq.mongodb.net:27017`

**Comment by Andruno** [comment]
Solved on stackoverflow
https://stackoverflow.com/questions/50949112/cant-add-serveratlas-cluster-in-mongo-explorer
