### ISSUE TITLE
How can we run mongo shell on remote machine?

### ISSUE THREAD

**Issue by pavelkalin** [dboissier/mongo4idea#223]
Thx for ssh login! Now I can access data and filter though it, but if I need to run any methods, I need to do it through mongo shell. It looks like a local shell is running not remote.

**Comment by dboissier** [comment]
Hi,

Technically, mongo shell iworks differently from the rest of the plugin (uses mongo-java-driver library). It iss just a system call wrapped in a View.  As alternative, you can use the `Terminal` feature to access your mongo instance through SSH.

I will study this enhancement.
