### ISSUE TITLE
bug : the same label cause nothing shows in the workspace.

### ISSUE THREAD

**Issue by toxmc** [dboissier/mongo4idea#230]
PhpStorm 2017.1.5
Build #PS-171.4694.83, built on March 8, 2018
Licensed to Rover12421
Subscription is active until December 31, 2099
JRE: 1.8.0_112-release-736-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.5

mongo4idea version 0.12.0
I was download 0.12.0 zip file to local. and unzip the file. 
I install the plugin from disk.  restart PhpStorm.

I add two servers with the same name for labels. that course nothing shows in the workspace.

I try to use file 0.11.0.zip reinstall plugin. that can get success.

**Comment by dboissier** [comment]
Hi,

The bug is known and the upcoming version will not allow having 2 same labels to prevent that.

Thx for reporting it.

**Comment by toxmc** [comment]
👍
