### ISSUE TITLE
Don't working in IDEA 2019.1 version

### ISSUE THREAD

**Issue by kas-cor** [dboissier/mongo4idea#250]
No response on "View collection content"

**Comment by hbenkhay** [comment]
same for me

**Comment by myperl** [comment]
same fpr me

**Comment by jpegram2** [comment]
Just upgraded to DataGrip 2019.1 on Mac Mojave and this is broken for me as well.

**Comment by Br0ce** [comment]
also no response on "View collection content"
with version 2019.1.2

**Comment by cunneen** [comment]
See if the zip I've attached to #269 fixes it for you:

[mongo4idea.zip](https://github.com/dboissier/mongo4idea/files/3300294/mongo4idea.zip)

**Comment by berga** [comment]
this zip fixes the issue for me on Rubymine 2019.1.3 OSX 10.14.5

**Comment by dboissier** [comment]
The plugin has been fixed and available on the Marketplace.

sorry for the delay

**Comment by kas-cor** [comment]
IntelliJ IDEA 2019.3 comes with long-awaited MongoDB support.
