### ISSUE TITLE
Please support mongodb+srv style connection configuration

### ISSUE THREAD

**Issue by Vampire** [dboissier/mongo4idea#257]
When setting up a server, you have to use the old-style `mongodb` protocol, specifying the single hosts of the cluster manually. It would be nice if the new-style `mongodb+srv` protocol would be supported where you give one host entry and it looks up via DNS SRV entries which actual hosts to connect to.

**Comment by dboissier** [comment]
Hi,

Jetbrains is currently working on the MongoDB support. This is great for all of us. Therefore I will not work on any new features for the plugin.

Thanks for your comprehension
