### ISSUE TITLE
Unable to open collection after updating intellij

### ISSUE THREAD

**Issue by meedeepak** [dboissier/mongo4idea#264]
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019

JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by neilchaudhuri** [comment]
+1

**Comment by MuscleGeeker** [comment]
+1

**Comment by daobeng** [comment]
Same here:

PyCharm 2019.1.1 (Community Edition)
Build #PC-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by Sailfishc** [comment]
+1

**Comment by elias-arnold** [comment]
Hi, same with DataGrip. 2019.1. on MacOS 10.14.4.
After downgrading DataGrip it works.

Thanks a lot for the plugin!

**Comment by chenxj1101** [comment]
+1

PyCharm 2019.1.1 (Professional Edition)
Build #PY-191.6605.12, built on April 3, 2019

JRE: 11.0.2+9-b159.34 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by dacopan** [comment]
+1

**Comment by dacopan** [comment]
my team currently working on fix this problem and release a new plugin version

**Comment by C500mg** [comment]
+1

**Comment by dacopan** [comment]
https://plugins.jetbrains.com/plugin/12242-mongo-2-0

**Comment by yangzhiw** [comment]
+1

**Comment by meedeepak** [comment]
> https://plugins.jetbrains.com/plugin/12242-mongo-2-0

Unable to download: 
The plugin update is pending JetBrains approval

**Comment by yehosef** [comment]
Why is this released as a new plugin and not just updating the old/current one?

**Comment by dboissier** [comment]
0.12.2 is available on the Plugin repository and seems to work (see #269).

Sorry for the delay :)
