### ISSUE TITLE
Plugin no longer maintained, is anyone willing to maintain it?

### ISSUE THREAD

**Issue by efstathiosntonas** [dboissier/mongo4idea#267]
It seems that this plugin is no longer maintained, since it has almost 600k downloads, I believe someone else should take over.

Is there anyone willing to do so?

@dboissier can you elaborate on this?

**Comment by dacopan** [comment]
my team currently working on fix this problem and release a new plugin version

**Comment by dboissier** [comment]
It seems to be ok (see #269)
