### ISSUE TITLE
Can not view data

### ISSUE THREAD

**Issue by ruanwenjun** [dboissier/mongo4idea#271]
when i click the table according to the README.md , i didn't see data of the table.
My machine is MacBook 2018 , My idea version is 2019.1 Ultimate Edition

**Comment by ni1son** [comment]
The same on windows 10.  I double click on it or pick "View collection content" in popup menu but collection doesn't open in tabs.

Mongo Plugin v0.12.0  
WebStorm 2019.1.2
Build #WS-191.7141.49, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ghukill** [comment]
Same behavior for me.  Can connect to database just fine, see the collections, but cannot view documents from collections when selecting "View collection content".

Mongo Plugin `v0.12.0`
WebStorm 2019.1.2
Build #WS-191.7141.49, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

**Comment by jpascal** [comment]
+1

**Comment by AdalWay** [comment]
I'm running a Linux machine with the last version of Intellig Idea and I have the same problem, I can't see my documents.

**Comment by Tangyiming** [comment]
+1 newest win10 ,newest Datagrip

**Comment by PabloMorales-syltek** [comment]
+1
Mongo Plugin v0.12.0
MongoDB shell version v4.0.3
Macos 10.14.5 (18F132)
openjdk version "11.0.3" 2019-04-16 LTS

**Comment by longye45** [comment]
+1

**Comment by Knapsack44** [comment]
+1

**Comment by mgarmhausen** [comment]
+1

**Comment by cunneen** [comment]
This could be a duplicate of #269 . You might want to try the zip I've attached to that issue (copied here):

[mongo4idea.zip](https://github.com/dboissier/mongo4idea/files/3300294/mongo4idea.zip)

**Comment by angussidney** [comment]
I'm also experiencing this issue in Pycharm 2019.1, Mongo Plugin v0.12.0, MongoDB shell version v4.0.10, on ElementaryOS Juno (based on Ubuntu 18.04)

**Comment by ruanwenjun** [comment]
@cunneen Thank you , this can solve my problem.

**Comment by Mancier** [comment]
@cunneen Thanks, worked for me too
