### ISSUE TITLE
How to set the ssh configuration with specific port.

### ISSUE THREAD

**Issue by javascriptDC** [dboissier/mongo4idea#272]
Hi.
I would like to check the remote data with specific port. I can not find anywhere to set the port number.
![Screenshot_2019-05-20_15:13](https://user-images.githubusercontent.com/33383467/57997819-05e48180-7b12-11e9-9c84-006d7fcadbdd.png)

Could you provide the link how to set the port, please?

**Comment by mancubus77** [comment]
It doesn't work, I've added pull request
https://github.com/dboissier/mongo4idea/pull/274

**Comment by foxbunny** [comment]
Any news on this?

**Comment by Grey2k** [comment]
@dboissier please check this pull request

**Comment by dboissier** [comment]
Merged :). I will add some tiny improvements (still have some freezes whenever the mongo server is unreachable or the connection is slow) before releasing the next version
