### ISSUE TITLE
When does the next release bundled?

### ISSUE THREAD

**Issue by xstable** [dboissier/mongo4idea#273]
Last Release here on GitHub was on 24 Jul 2018.
When does the next release will be bundled?

**Comment by dboissier** [comment]
Hi,

the plugin has been fixed. please download this [release](https://github.com/dboissier/mongo4idea/blob/master/snapshot/mongo4idea-0.12.2-SNAPSHOT.zip) and tell me whether it works on your IDE.

Thanks

**Comment by dboissier** [comment]
It seems to be ok (see #269)

**Comment by xstable** [comment]
Please tell the Plugin-Version where is it fixed, so that everybody can be sure to have the right plugin installed.
