### ISSUE TITLE
how to use it in datagrip?

### ISSUE THREAD

**Issue by JeffcottLu** [dboissier/mongo4idea#276]
couldn't find where to add a Mongo Server in datagrip, pls help

**Comment by ChengChuanxin94** [comment]
@JeffcottLu when u installed the plugin ,and restart datagrip ,then u can see the button 'Mongo Explorer' on the right side

**Comment by JeffcottLu** [comment]
> @JeffcottLu when u installed the plugin ,and restart datagrip ,then u can see the button 'Mongo Explorer' on the right side

thx, i've found this
