### ISSUE TITLE
Plugin not useful in IDEA 2019.1

### ISSUE THREAD

**Issue by bkahlerventer** [dboissier/mongo4idea#278]
Only part that is functional is the mongo explorer.  View Collection Content not working.  No errors given.

**Comment by ycj** [comment]
FLS

**Comment by apomarinov** [comment]
:( just started working with mongo. This plugin looked like what I was looking for. All the other GUIs are lacking...

**Comment by kosaa** [comment]
Idea 2019.2 same problem,

collections are listed but 'view collection content' doesn't works

Additional info about selected collection is display correctly

**Comment by yufeicheng** [comment]
idea 2019.2  same problem ,  view collection content  don't work

**Comment by nicholsmarkd** [comment]
using PyCharm 2019.2.1
successful connect to DB and view collection stats
failed viewing collection content. No error, no apparent response from IDE.

**Comment by dboissier** [comment]
Hi,

the plugin has been fixed. please download this [release](https://github.com/dboissier/mongo4idea/blob/master/snapshot/mongo4idea-0.12.2-SNAPSHOT.zip) and tell me whether it works on your IDE.

Thanks

**Comment by dboissier** [comment]
It seems to be ok (see #269)
