### ISSUE TITLE
Query by ObjectId()

### ISSUE THREAD

**Issue by pdelanauze** [dboissier/mongo4idea#28]
I don't seem to be able to perform a query by object id , such as :

`
{my_id: ObjectId('50d1e99f128ca529e40000a4')}
`

**Comment by akademy** [comment]
Great - but even better : this little tip should be in the documentation!

**Comment by banxi1988** [comment]
`{_id: {$oid: '50d1e99f128ca529e40000a4'}}`
This tip really should  be in the documentation.
I have had waste a lot of time on google it.
