### ISSUE TITLE
View Collections is not working

### ISSUE THREAD

**Issue by 3dvirtuallabs** [dboissier/mongo4idea#280]
I have installed 
![image](https://user-images.githubusercontent.com/2582649/63920247-06b87800-ca5e-11e9-9cd1-2498fcd244ed.png)

and when I click on view collection in mongo explorer it doesn't do anything? It may be a duplicate but any expected time for a solution?

**Comment by upwan111** [comment]
Same problem I am facing.

**Comment by efstathiosntonas** [comment]
Duplicate of https://github.com/dboissier/mongo4idea/issues/269

**Comment by 3dvirtuallabs** [comment]
@efstathiosntonas I have mentioned it already but there is no response on either one of the duplicates.

**Comment by efstathiosntonas** [comment]
On #269 you can find a .zip file with a working version. Just uninstall official plugin then manually install .zip by selecting “install plugin from disk”. 

ps. Do not extract the zip file.

**Comment by 3dvirtuallabs** [comment]
> On #269 you can find a .zip file with a working version. Just uninstall official plugin then manually install .zip by selecting “install plugin from disk”.
> 
> ps. Do not extract the zip file.
> 
> Edit: here’s the file [#269 (comment)](https://github.com/dboissier/mongo4idea/issues/269#issuecomment-502984541)

![image](https://user-images.githubusercontent.com/2582649/64074558-7894f980-ccca-11e9-8252-883061b534cf.png)

**Comment by 3dvirtuallabs** [comment]
great, thanks a lot.
