### ISSUE TITLE
Add a Mongo Server + specify database

### ISSUE THREAD

**Issue by cloudermaan** [dboissier/mongo4idea#31]
Hello, 

Nice interface for adding/managing server connections.

I notice that the plugin does not work when on a server you can view only one specific database.

From console I connect with 
mongo localhost:27017/restricteddatabase -u user -p mypassword

I tried specifying --nodb in arguments list but still get Invalid credentials.(the credentials are good but do not have full access).

**Comment by tmundt** [comment]
Does the actual version work with MongoLab? I am unable to get a connection. I am using version number 0.7.6 of the plugin and try to connect to a MongoDB at MongoLab remotely with version number 3.2.10. I get a auth-error with number 18.
