### ISSUE TITLE
Password should not be "required" in storing a server

### ISSUE THREAD

**Issue by oliverganz** [dboissier/mongo4idea#56]
I would like to be inconvenient for myself.
=> for live data I would love to paste my password each time I connect to the server, to make sure I don't accidently connect to it (thinking I connect to local)

If I connect to a server afterwards, that did not yet have a password: ask me for it

**Comment by dboissier** [comment]
Hi,

I will make this feature in the upcoming nosql4idea plugin (Mongo, Redis and Couchbase integration). Sorry for the inconvenience.

David
