### ISSUE TITLE
Using a custom dbpath?

### ISSUE THREAD

**Issue by ArEnSc** [dboissier/mongo4idea#84]
hey I am using a --dbpath that is not the default path that mongo uses, and it appears not to populate my mongoserver explorer view how do I handle this error?

**Comment by metasean** [comment]
To connect Mongo Explorer to your specific Mongo instance:
From the Mongo Explorer tab, open the Preferences window (it looks like this could also be reached through WebStorm's Preferences, then Other Settings, Mongo Servers).  In the "Path to Mongo executable", navigate to your db directory, then select the mongod.lock file.


![untitled copy](https://cloud.githubusercontent.com/assets/7552754/6428894/c3fcbf96-bf70-11e4-8cc2-120c4fa167ec.jpg)


@chrisjacob - I have no idea how to have WebStorm start up MongoDB automatically.  If you have found a way, please post it!

**Comment by dboissier** [comment]
Hi,

actually, you have to specify mongo cli path (e.g.: /usr/bin/mongo) not the mongo daemon. Perhaps, the doc is unclear for that point. So, I will update it.
