### ISSUE TITLE
How to query by date?

### ISSUE THREAD

**Issue by hbomze** [dboissier/mongo4idea#86]
I tried querying using something like {"createdAt": {"$gte":new Date(2014, 1, 1)}} which works in the Mongo shell, but get an error.  I also tried it without the new and also got an error.  Is there a way I can query but date?

Thanks.

**Comment by obiwarn** [comment]
@dboissier Thank you. It would be great to have this in the docs.

**Comment by dboissier** [comment]
ok

**Comment by rjmunhoz** [comment]
Sorry for necro posting, but the following syntax didn't bring any results up, while issuing the query using `ISODate` on the shell did bring me stuff.

Is there any problem with the syntax here?

```json
{"$match": {"date": {"$gte": {"$date": "2017-07-01"}, "$lte": {"$date": "2017-08-01"}}}},
{"$project": {"date": 1}}
```
