### ISSUE TITLE
Support for Projections while querying.

### ISSUE THREAD

**Issue by dharmeshkakadia** [dboissier/mongo4idea#87]
I love the plugin. Thanks for it.
I was wondering if projections support can be added, allowing users to control what fields to return.

**Comment by dboissier** [comment]
Hi,

New query panel available [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-distribution.zip)

Please tell me if it is ok for you.

David

**Comment by dharmeshkakadia** [comment]
@dboissier Thanks. I have moved to Idea 14. Does this work on 14?

**Comment by dboissier** [comment]
Not yet. I am on it and it should be available by the end of today

**Comment by dboissier** [comment]
Hi,

I uploaded a [snapshot](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) version tested on Webstorm 9. It should work on Idea 14 too.

Please tell me if it works on your IDE.

David

**Comment by dharmeshkakadia** [comment]
@dboissier I tried it on idea 14.0.3 and it works perfect !! Thanks a lot :)

**Comment by dboissier** [comment]
Great.

When you have time, please, provide me some UX feedback on the query panel.

cheers

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository
