### ISSUE TITLE
Support for SSL encrypted connections to MongoDb instances

### ISSUE THREAD

**Issue by fenixcitizen** [dboissier/mongo4idea#90]
Hello, 

cannot see any option to enable SSL encryption. If it is not supported at the moment, it would be great to add it. This is the only reason why I need to use other mongodb clients...

**Comment by dboissier** [comment]
Hi,

SSL Support available [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-distribution.zip).

I do not have any secured mongo instance for testing . Please tell me if it works on your side.

David

**Comment by dboissier** [comment]
Hi,

Idea14/Webstorm9 version is also [available](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip).

Please tell me if it works on your IDE.

David

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository
