### ISSUE TITLE
UnsupportedOperationException viewing collection

### ISSUE THREAD

**Issue by mennis** [dboissier/mongo4idea#97]
Using 0.6.1 on a Mac in Pycharm 4 (139-673)

11:01:06 AM VCS Update Finished
            11 Files Updated
            14 Files Created
            2 Files Deleted
1:03:57 PM UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
1:04:03 PM UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
1:04:06 PM UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
1:04:08 PM UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile
1:05:27 PM Error Report
           Submitted as 763966.
           Thank you for your feedback!
1:05:27 PM UnsupportedOperationException: org.codinjutsu.tools.mongo.view.editor.MongoObjectFile

Traceback:
    https://gist.github.com/mennis/c7f3043d840b8f445981

**Comment by dboissier** [comment]
Hi,

fixed version available [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-distribution.zip).

Tell me if it s ok

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository
