### ISSUE TITLE
auto-refresh when documents get added/removed/edited

### ISSUE THREAD

**Issue by markusgattol** [dboissier/mongo4idea#98]
Toying around on a meteor project in webstorm (https://github.com/meteor/simple-todos) I noticed that when I add a new task to the todo list (the task collection), the open tab showing the mongodb task collection does not auto-update to show the newly added task.

I have to reopen the task collection anew in a new mongo explorer tab in webstorm to see the task document. Is this to be expected or can I flip a config switch in webstorm, having the plugin and thus webstorm monitor CRUD actions to the database and display them right away without the need for a manual refresh of open mongo explorer tabs?

**Comment by dboissier** [comment]
Hi,

it is available in this [SNASPHOT](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.7.0-SNAPSHOT-distribution.zip).

Could you please install it and tell me if it is ok ?

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository
