### ISSUE TITLE
Dates being translated to timezone

### ISSUE THREAD

**Issue by m2calabr** [dboissier/mongo4idea#99]
When you are looking at the dates in the collection view, the dates are shown in the machine's timezone.  As a developer I would really like to see how the dates are stored.  

If there is a need to view the date in the machine's timezone then can there be a configuration setting to set what timezone to display the date in.

**Comment by dboissier** [comment]
Hi,

This seems to be highly relevant. I will look at it.

Thanks for your suggestion.

**Comment by dboissier** [comment]
I suggest to format date in UTC. What do you think about it?

**Comment by m2calabr** [comment]
That would be great and works for me well as I try and store all of my
times in UTC.  That would also be great in that you see what is actually
see the data in the database.

There might be some developers that are storing local time and then they
would have to hand convert.

I would still think that having the data in the plugin match what you would
get when you do a find in the database.

Does that make sense?


On Tue, Feb 24, 2015 at 7:24 AM, David Boissier <notifications@github.com>
wrote:

> I suggest to format date in UTC. What do you think about it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dboissier/mongo4idea/issues/99#issuecomment-75776531>.
>



-- 
*Michael Calabrese*
Senior Developer

*Lunar Logic - go further*

Phone: (541) 357-6721
Toll-Free: (877) 861-0351
Web: www.lunarlogic.com

**Comment by dboissier** [comment]
Hi,

Date is displayed in UTC (edition too).
Snapshots links are available on the github project home page.

Please tell me if it is ok.

**Comment by m2calabr** [comment]
David,
Thank you for being so responsive.  I downloaded the two snapshots and they
are incompatible with my version of phpStorm.  I am running the latest
PHPStorm 8.0.3 (#PS-139.1349).

Also I am excited to hear out the new plug-in that covers more DBs.  If you
need any help testing with it and PHPStorm and MongoDB, please let me know.



On Tue, Feb 24, 2015 at 9:39 AM, David Boissier <notifications@github.com>
wrote:

> Hi,
>
> Date is displayed in UTC (edition too).
> Snapshots links are available on the github project home page.
>
> Please tell me if it is ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dboissier/mongo4idea/issues/99#issuecomment-75804746>.
>



-- 
*Michael Calabrese*
Senior Developer

*Lunar Logic - go further*

Phone: (541) 357-6721
Toll-Free: (877) 861-0351
Web: www.lunarlogic.com

**Comment by dboissier** [comment]
Ok,

I will check that incompatibility tomorrow around 2015/02/25 10:00:00 UTC ;)

**Comment by dboissier** [comment]
Hi,

I just installed PhpStorm 8.0 and the plugin (mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) and it works fine.

Any info or stacktrace you could provide me?

Thanks

**Comment by m2calabr** [comment]
It will be a bit before I can try.  I will get you the results by tomorrow.

On Wed, Feb 25, 2015 at 4:12 AM, David Boissier <notifications@github.com>
wrote:

> Hi,
>
> I just installed PhpStorm 8.0 and the plugin
> (mongo4idea-0.7.0-SNAPSHOT-Idea14-distribution.zip) and it works fine.
>
> Any info or stacktrace you could provide me?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dboissier/mongo4idea/issues/99#issuecomment-75949908>.
>



-- 
*Michael Calabrese*
Senior Developer

*Lunar Logic - go further*

Phone: (541) 357-6721
Toll-Free: (877) 861-0351
Web: www.lunarlogic.com

**Comment by dboissier** [comment]
Release 0.7.0 available on Jetbrains plugin repository

**Comment by m2calabr** [comment]
FYI,
Since you did the update, I installed it and the results look great.

Thank you for you help!
Michael

On Wed, Feb 25, 2015 at 9:13 AM, David Boissier <notifications@github.com>
wrote:

> Closed #99 <https://github.com/dboissier/mongo4idea/issues/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dboissier/mongo4idea/issues/99#event-241861823>.
>



-- 
*Michael Calabrese*
Senior Developer

*Lunar Logic - go further*

Phone: (541) 357-6721
Toll-Free: (877) 861-0351
Web: www.lunarlogic.com
